### PR TITLE
get fife version to switch API

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
At commit https://github.com/unknown-horizons/unknown-horizons/commit/0280e7a758721da2ef95a4cfc85f1d4c5faadee5 was the API from fifengine change, some developer use the newest version, but Travis CI use a little bit older version so Travis fail.  
To use the newest fifengine version, make sure that is highter than 0.4.1, with this change can work Travis  with 0.4.1 and developer with a newer version.
To see the tarvis build change: https://github.com/MarkusHackspacher/unknown-horizons/commits/fifeversion

### CODE REVIEW

**Comment by AndyMender** [comment]
Yes, we are aware the version on Travis CI is outdated and we'll get a new one up as soon as we can.

**Comment by MarkusHackspacher** [comment]
>  Imho this should be preferable than supporting multiple versions of FIFE.

The code from unknown-horizons supports already multiple versions of FIFE.
https://github.com/unknown-horizons/unknown-horizons/search?utf8=%E2%9C%93&q=getversion&type=

**Comment by nihathrael** [comment]
Maybe we should remove all of these?

**Comment by LinuxDonald** [comment]
Yes please remove them all. We don't support old fife version with master.

**Comment by LinuxDonald** [comment]
Done with https://github.com/unknown-horizons/unknown-horizons/commit/e614e9c6cabdeceac0bbb7756316799bc36afbe0

@nihathrael please review this commit.

**Pull request closed without merging**
