### PR TITLE
Update test_platform.py

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
in the https://github.com/unknown-horizons/unknown-horizons/commit/d7bbacaa1d71fb48fa21b15515750a5e11178c80 use new paths and migrate files if necessary, this PR change it in the test, too.

### CODE REVIEW

**Comment by jmdejong** [comment]
The functions have changed more than just the names.
`get_user_game_directory()` returned a filepath as PurePath object.
`get_user_game_directories()` returns a tuple of filenames as strings.

**Comment by MarkusHackspacher** [comment]
But get_user_game_directory() was remove in https://github.com/unknown-horizons/unknown-horizons/commit/d7bbacaa1d71fb48fa21b15515750a5e11178c80#diff-66fd2e9bb43737f7ec6bbb16a384dc5dL43

**Comment by MarkusHackspacher** [comment]
I tested it at my computer and that work fine, but travis fail

```
$ pytest-3 tests/unittests/util/test_platform.py 
====================================================== test session starts =======================================================
platform linux -- Python 3.6.5rc1, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
rootdir: /home/mar/workspace/python/src/unknown-horizons, inifile:
plugins: mock-1.7.1, cov-2.5.1
collected 2 items                                                                                                                

tests/unittests/util/test_platform.py ..                                                                                   [100%]

==================================================== 2 passed in 0.02 seconds ====================================================
```

**Comment by jmdejong** [comment]
There seem to be some more problems with the path tests, but that's probably out of the scope of this PR

**Pull request merged**
