### PR TITLE
added pr 2334 and pr 2335 from Gladius1

### PR DESCRIPTION
**Pull request by LinuxDonald**
Added both pr from Gladius1 to an clean branch. I hope i dont have forgot anything :)

### CODE REVIEW

**Comment by Gladius1** [comment]
Thank you.

**Comment by stubb** [comment]
We have to add an entry to the doc/LICENSE file for each sound file, if they are not made by Gladius1.

**Comment by stubb** [comment]
wav files are not supported. It have to converted to an ogg file. Maybe via audacity.

**Comment by stubb** [comment]
I would lower the volume of the market.ogg. Its really dominant ingame.

**Comment by LinuxDonald** [comment]
stubb should I fixed both or are you working on it?

**Comment by stubb** [comment]
I will fix it. After we know if we can include the sounds in the game. So we need to know where are the sound files from first.

**Comment by stubb** [comment]
@Gladius1 can you provide the necessary information please?

**Comment by LinuxDonald** [comment]
here are the license for the files

**Comment by stubb** [comment]
Looks like a copy&paste went wrong?

**Comment by Gladius1** [comment]
So what needs to be done next? Convert .wav to .ogg? License?

**Comment by Gladius1** [comment]
https://freesound.org/people/ivolipa/sounds/266511/
This is the missing link for the dogs_barking.wav file.

**Comment by LinuxDonald** [comment]
https://github.com/Gladius1/unknown-horizons/commit/6eb1a8e3ee667379f06e54f48f02d37086af9fef

**Comment by LinuxDonald** [comment]
link is above

**Comment by LinuxDonald** [comment]
stubb please join irc i need you

**Comment by stubb** [comment]
The file https://freesound.org/people/kyles/sounds/177524/
has to be removed from this pull request, because it is not DFSG compatible, see https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution-Non_Commercial-Share_Alike_.28CC-by-nc-sa.29

Same for the file https://freesound.org/people/Splifffy/sounds/262048/, https://freesound.org/people/Andune/sounds/86276/ and https://freesound.org/people/ivolipa/sounds/266511/

In the past we made major changes to achieve this compatibility. Sorry that we can not include it into Unknown Horizons. It would result in the re movement of the game from the Debian repositories.

**Comment by LinuxDonald** [comment]
Added toolmaker ond market audio file from Ollo only cow and windmill are left than we can merge that work :)

**Comment by LinuxDonald** [comment]
Thanks for your work @Gladius1 and @Ollo123 :)

**Pull request merged**
