### PR TITLE
Some changes to: add_weblate_language.sh

### PR DESCRIPTION
**Pull request by LinuxDonald**
Fixed add_weblate_language.sh that it works from development folder
Added command for create The_Unknown scenario po files

@MasterofJOKers please review it and when you want expand it

### CODE REVIEW

**Comment by MasterofJOKers** [comment]
Two things:
* Why? You could just run `development/add_weblate_language.sh` instead. Keeping it that way would also support moving the script to another place like e.g. `development/translation/`. I think the assumption, that a script is running from the root-folder of UH is not a bad one.
* You have two distinct/separate changes in the same commit. It should be two commits. One for the first line of you commit message and the second one for the second line of you commit message.

**Comment by MasterofJOKers** [comment]
Other than that: We should not use explicit names for the scenarios, but just copy all scenarios. So please convert this into a for-loop. This would also get rid of the second, not needed `mkdir -p`.

**Comment by MasterofJOKers** [comment]
Sorry, just read, that I'm supposed to expand it. Will do it later today, I guess.

**Comment by LinuxDonald** [comment]
Thx @MasterofJOkers :-)

**Pull request merged**
