### PR TITLE
Fix crash on missing thumbnails in unit queue

### PR DESCRIPTION
**Pull request by Teemperor**
How to reproduce:

1. Build barracks
2. Start building swordsmen
3. Start building another swordsmen
4. Crash due to missing swordsmen thumbnail for the que

This patch fixes this by using a fallback image. I kept the patch generic because we probably get more of these problems when we can produce different units.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
We know that it is broken. @stubb is working on the unit production. Thx for the patch. But maybe we will fix the crash directly.

**Comment by Teemperor** [comment]
I'll keep it open for now. Feel free to close it if it superseded by another PR

**Comment by stubb** [comment]
My own solution was providing an thumbnail, but I like the idea of using an exception. Similar approach is used for imagebuttons. @Teemperor I would appreciate a related PR for the fifengine

**Comment by stubb** [comment]
Thanks for this PR :+1:

**Pull request merged**
