### PR TITLE
Stance and stub for new ships

### PR DESCRIPTION
**Pull request by LinuxDonald**
Needs testing

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@AndyMender could you please review the python code part of this pr? I dont have tested it yet. I hope i can do it on the weekend :)

**Comment by LinuxDonald** [comment]
@nihathrael @AndyMender please review this.

**Comment by AndyMender** [comment]
@LinuxDonald the code in general looks alright, but is it safe to remove the `Fife` import from some files? Also, the merges from master may occlude some changes (more recent code from master overwriting stuff from this branch) so I would test this directly  as well.

**Comment by LinuxDonald** [comment]
@AndyMender the remove fife imports got into the wrong branch its already in master because of the commit before it. I hope i dont have broken something.

**Comment by LinuxDonald** [comment]
@AndyMender rebase is done. Its now ready for review :)

**Comment by AndyMender** [comment]
@LinuxDonald just looking at the code, it seems alright. Maybe some in-game testing to make sure nothing is awfully broken?

**Pull request merged**
