### PR TITLE
Consider set comprehensions instead of passing lists to 'set()'

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
change set([x for (x, _) in self.land_manager.village]) to {x for (x, _) in self.land_manager.village}

https://www.quantifiedcode.com/app/issue_class/2e5IzmR1

### CODE REVIEW

**Comment by MasterofJOKers** [comment]
I'm not sure about what we decided, but python2.6 does not seem to support that type of syntax.
```python
>>> a = [1, 2, 3, 3]
>>> {x for x in a}
  File "<stdin>", line 1
    {x for x in a}
         ^
SyntaxError: invalid syntax
>>> set(x for x in a)
set([1, 2, 3])
```

**Comment by MasterofJOKers** [comment]
@LinuxDonald told me, we're not supporting python2.6 any more. So that's fine.

I'd still prefer the `set()` over the `{}` as it's more explicit. But that's probably more because of me not using `{}` much.

**Comment by MarkusHackspacher** [comment]
I have only one argument, it is faster.
But the set() it easier to read. Maybe help inline comments.

```
>>> import timeit
>>> timeit.timeit('{x for x in [1, 2, 3, 4]}')
0.5454318523406982
>>> timeit.timeit('set(x for x in [1, 2, 3, 4])')
0.8383378982543945
>>> timeit.timeit('{x for x in [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]}')
1.1321148872375488
>>> timeit.timeit('set(x for x in [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])')
1.6722140312194824
```

**Comment by LinuxDonald** [comment]
Maybe add an comment for easier understanding in the code?

**Comment by MasterofJOKers** [comment]
No comment necessary to explain syntax.

You're right. It's about 200 ns faster on my system. So if that function is called very very often, that would make a difference.

**Comment by LinuxDonald** [comment]
@MasterofJOKers is that ready for merge? And can that pushed too into python3 branch?

**Comment by MasterofJOKers** [comment]
@LinuxDonald Not by you, no. @ChrisOelmueller said something about it on IRC regarding the removal of the line, that seems to do nothing. It should go in its own commit. So ... I could probably merge it if I wouldn't be playing right now.

**Comment by MasterofJOKers** [comment]
merged

**Pull request closed without merging**
