### PR TITLE
Fix space issues in production overview

### LINKED ISSUE #2169: Settlement production overview overflow
With large settlements, the space provided there is not enough.
Should either be scrollable, or find a better way of representing the information.

show me

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1205559-settlement-production-overview-overflow?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by squiddy**
Fixes #2169 

- [x] fix page scrolling
- [x] add more padding, use more whitespace (that means less than 19 rows per page)
- [x] handle hidden resources (avoid creating blank space and switching to next page too early)

### CODE REVIEW

**Comment by LinuxDonald** [comment]
The second page is displayed two times. On the first pages its all okay but on when you click and go to the third page you see the second page again. (sorry for bad english)

**Comment by squiddy** [comment]
@LinuxDonald Can you please attach the samegame you used for the screenshots?

**Comment by LinuxDonald** [comment]
[test-squiddis-overview-pr.sqlite.tar.gz](https://github.com/unknown-horizons/unknown-horizons/files/551433/test-squiddis-overview-pr.sqlite.tar.gz)

For you squiddys i do all :)

**Comment by squiddy** [comment]
Make it look nicer by introducing more whitespace

production-overview-layout

**Comment by LinuxDonald** [comment]
From me :+1: for merge

**Pull request merged**
