### PR TITLE
add codestyle settings

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
E113 unexpected indentation
 E125 continuation line with same indent as next logical line

### CODE REVIEW

**Comment by squiddy** [comment]
Looks good to me.

**Comment by LinuxDonald** [comment]
@squiddy could you approve the pr and merge it please

**Comment by squiddy** [comment]
@MarkusHackspacher can you rebase this onto current master? Thanks

**Comment by squiddy** [comment]
Resolved the conflict myself and merged.

**Pull request merged**
