### PR TITLE
Avoid using `len(x)` to check if a list is empty

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
I change the code to make the running time faster.
Travis need for the code check now 49.242s to 49.900s. The other check need 61s to 69s.
I hope that it was not an (travis)exception, it can anyone confirm?

### CODE REVIEW

**Comment by LinuxDonald** [comment]
When travis I'd faster I'd than the game maybe a bit faster too? MasterofJOKers is now 2 weeks not here (vacation)

**Comment by LinuxDonald** [comment]
I found the len is an python fuction https://docs.python.org/2/library/functions.html#len is len here needed or can it be really removed?

**Comment by MarkusHackspacher** [comment]
https://www.quantifiedcode.com/app/issue_class/3LKECaRv
or https://doc.odoo.com/contribute/15_guidelines/coding_guidelines_python/#collections-are-booleans-too

**Comment by LinuxDonald** [comment]
thx for the info i will test the change later. If there are no problems i will merge that :)

Thx for your work :+1:

**Comment by LinuxDonald** [comment]
Found no problems :) Thank you for the patch :+1:

**Pull request merged**
