### PR TITLE
Use git describe for version detection

### PR DESCRIPTION
**Pull request by squiddy**
mainmenu-version
### TODO
- [x] Test git describe on windows

### CODE REVIEW

**Comment by squiddy** [comment]
Tested successfully under Windows 7 Enterprise, Python 2.7.12, git 2.10.1.

**Comment by LinuxDonald** [comment]
Before we pull this pr we should make new tag for the version.

**Comment by squiddy** [comment]
I don't understand how that is related. This extends the version detection by adding the tag name, if available. Nothing more.

**Comment by squiddy** [comment]
Also this code isn't relevant for releases, only for git checkouts. Releases get their version number hardcoded.

**Comment by LinuxDonald** [comment]
Okay

**Comment by jorgesumle** [comment]
Works fine on GNU/Linux. I'm running _Trisquel 7.0_.

**Comment by LinuxDonald** [comment]
👍 For merge

**Comment by krichter722** [comment]
Why hasn't this been merged? It's useful for orientation in development builds. Please start using git tags.

**Comment by ChrisOelmueller** [comment]
It was merged, cf. e75c9ae2c26a33a040b1cf3afec9c6baf46be33e

**Comment by LinuxDonald** [comment]
Our lastest git tag is version 2014.x because since this version we dont had yet released an new one. The next will be 2017.1 but i cant say you yet an date.

**Comment by krichter722** [comment]
> It was merged, cf. e75c9ae

Good to know. Thank you.

> Our lastest git tag is version 2014.x because since this version we dont had yet released an new one. The next will be 2017.1 but i cant say you yet an date.

I see the tags in `git tag`, but `git describe` says `fatal: No tags can describe 'e7e701c9334a8680c1ad96fe09ba7f52eddd6dd0'.`. I usually have this issue if tags are used on branch different from master (e.g. if a projects decides to do so) (see also http://stackoverflow.com/questions/4154485/git-describe-ignores-a-tag).

We can discuss this in another issue if you want.

**Comment by ChrisOelmueller** [comment]
That happens because the (to me, questionable) default of `git describe` is to disregard tags that are not annotated. Include the `--tags` flag to change that behavior and also find light (un-annotated) tags, which I'd expect the majority of recent tags to be.

**Comment by krichter722** [comment]
> That happens because the (to me, questionable) default of git describe is to disregard tags that are not annotated. Include the --tags flag to change that behavior and also find light (un-annotated) tags, which I'd expect the majority of recent tags to be.

`git describe --tags` fails due to the same error.

**Comment by krichter722** [comment]
>> That happens because the (to me, questionable) default of git describe is to disregard tags that are not annotated. Include the --tags flag to change that behavior and also find light (un-annotated) tags, which I'd expect the majority of recent tags to be.
>
> git describe --tags fails due to the same error. I assume git fetch --tags fetches all types of tags.

Works fine now as of 2014.1-1013-g9797b7127 (possibly earlier).

**Pull request closed without merging**
