### PR TITLE
Corrected some errors and ambiguities from the english text in the tu…

### PR DESCRIPTION
**Pull request by jorgesumle**
…torial.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Why this pull request have conflicts..... I will take an look tomorrow on it. Maybe at the next pr take only the yaml files for easier review.

**Comment by MasterofJOKers** [comment]
@jorgesumle How did you re-generate the *.po files?

**Comment by jorgesumle** [comment]
I think because someone submitted an Ukranian translation, and I forgot to make `git pull upstream`. You can resolve them easily from Github. Today, I'm busy, but tomorrow, I you have any problem resolving the pull request, I'll fix that.

**Comment by LinuxDonald** [comment]
fixed and merged with: https://github.com/unknown-horizons/unknown-horizons/commit/2854ac350fb1cb52c2e58a7c64c8bbbddc17e9e9

**Comment by LinuxDonald** [comment]
Okay not fixed. Forgt to do ./development/create_scenario_pot.sh tutorial

but it fails with:

Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
KeyError: 0

**Comment by LinuxDonald** [comment]
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./development/create_scenario_pot.sh tutorial
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "/usr/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/site-packages/yaml/scanner.py", line 212, in fetch_more_tokens
    return self.fetch_block_entry()
  File "/usr/lib/python2.7/site-packages/yaml/scanner.py", line 494, in fetch_block_entry
    self.get_mark())
yaml.scanner.ScannerError: sequence entries are not allowed here
  in "content/scenarios/tutorial_en.yaml", line 224, column 120

**Comment by LinuxDonald** [comment]
Now its really done sorry :( https://github.com/unknown-horizons/unknown-horizons/commit/12b1147c9e027051b5393846db43c1032e4602b6

**Pull request closed without merging**
