### PR TITLE
Ai update buildings [NOT DONE]

### PR DESCRIPTION
**Pull request by LinuxDonald**
DONT MERGE IT.
Its not done.
- [ ] AI code for Woden Tower
- [ ] AI code for Hunter
- [ ] let the ai build the new buildings

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Branch is broken and i dont know why :(

[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py       
The Python Imaging Library (PIL / Pillow) package is needed to run the atlas generator.
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Failed to load content/maps/quattro.sqlite
Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 378, in start_singleplayer
    _modules.session.load(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/spsession.py", line 43, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 252, in load
    options.init_new_world(self)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/util/startgameoptions.py", line 60, in init_new_world
    center = session.world.init_new_world(self.trader_enabled, self.pirate_enabled, self.natural_resource_multiplier)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 461, in init_new_world
    AIPlayer.load_abstract_buildings(self.session.db) # TODO: find a better place for this
  File "/home/linuxdonald/dev/unknown-horizons/horizons/ai/aiplayer/__init__.py", line 487, in load_abstract_buildings
    AbstractBuilding.load_all(db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/ai/aiplayer/building/__init__.py", line 78, in load_all
    cls.buildings[building_id] = class_ref.load(db, building_id)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/ai/aiplayer/building/__init__.py", line 93, in load
    return cls(building_id, name, settler_level)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/ai/aiplayer/building/__init__.py", line 55, in __init__
    self.__init_production_lines()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/ai/aiplayer/building/__init__.py", line 65, in __init_production_lines
    assert len(production_line.produced_res) == 1
AssertionError
function is no-op

**Comment by LinuxDonald** [comment]
@MarkusHackspacher could you maybe help me again :)
Long no tested the branch and dont know was get broken here :(

**Comment by MarkusHackspacher** [comment]
At commit 3920131 was all ok, but one later in 65476ef happen the fault, look what is change and make step by step backward to locate the error. 
https://github.com/unknown-horizons/unknown-horizons/pull/2387/commits/65476ef75f586b8f5a6f543c9b8f7af142007f8e

I take a look to all files of the pull request, but I see not only 1 comment and the lines are to long, too.

**Comment by squiddy** [comment]
@LinuxDonald 

```
File ".../horizons/ai/aiplayer/building/__init.py", line 65, in __init_production_lines
assert len(production_line.produced_res) == 1
```

The error message says it all actually, the `AbstractBuilding` in `ai/aiplayer/building/__init__.py` seems to have been written with one produced resource per production line. However, in 65476ef you added two resources for lines `HONEYCOMBS_COCOA` and `HONEYCOMBS_GRAPES`.

**Pull request closed without merging**
