### PR TITLE
remove unused import

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
I have remove unused import pytest from the last PR #2705 .

### CODE REVIEW

**Comment by AndyMender** [comment]
> I have remove unused import pytest from the last PR #2705 .
Pull request #2705 is related to fixing building actionset offsets. What you actually linked is squiddy's possible work-in-progress concerning multiplayer tests. @squiddy is that correct?

**Comment by MarkusHackspacher** [comment]
Sorry, not the PR, the commit 'Extract server statistics into separate function' https://github.com/unknown-horizons/unknown-horizons/commit/f5c92303569ba47806714b4b927ca5fe2e04dcfa

**Comment by AndyMender** [comment]
Regardless, I will wait for the opinion of @squiddy if you don't mind :).

**Comment by squiddy** [comment]
Looks good to me.

**Pull request merged**
