### PR TITLE
fix some select memory leak bugs, partly resolve issue #2308

### PR DESCRIPTION
**Pull request by pinkfloyda**
The game can be played longer, but still found 60+ icons or supported listeners not gced each selection.

### CODE REVIEW

**Comment by stubb** [comment]
Great investigations, thanks for your work! There is further work needed, but its on a good way. I recommend to do smaller commits and maybe a single PR for the tab hide stuff, which seems already in a good shape. You also can use git rebase to squash the merge commit.

**Comment by pinkfloyda** [comment]
@stubb Welcome, :-), it's be a long time since last play and commit. The mem blow up after playing for a while is quite irritating, just want to help it out.

**Comment by nihathrael** [comment]
Thanks for the great contribution!

**Comment by stubb** [comment]
This PR introduces #2321.

**Pull request merged**
