### PR TITLE
Production Overview fix

### PR DESCRIPTION
**Pull request by Gladius1**
I fixed the bug that the production overview was empty.  Production Overview is broken #2369 
Once we have buildings that produce units or ships, this has to be reverted.

### CODE REVIEW

**Comment by stubb** [comment]
The boatbuilder and barracks buildings are unit/ship producer. Your fix simply tries to display all produced resources including units now. I think we need a better approach to fix this. Your help is really appreciated!

**Comment by Gladius1** [comment]
This should work. The bug was, that all components had the name "producer". Since the names were equal the condition wasn't met and the def to update the settlement inventory wasn't called.

**Comment by Gladius1** [comment]
Please check out my tooltip fix as well.

https://github.com/Gladius1/unknown-horizons/tree/tooltip-fix-gladius

**Comment by stubb** [comment]
@Gladius1 please open another PR for the tooltip fix

**Comment by stubb** [comment]
About the overview. It does not work, because it tries to display all produces "resouces" now. Including the units. A good solution would be to only display produced resources from Producer not UnitProducers of any kind.

**Comment by stubb** [comment]
Sorry, did not saw your last commit. But this introduces other issued where we check if a building has the component Producer, like here https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/world/building/buildingresourcehandler.py#L53. Components are identified by the name. Your commit introduces two new components and the check fails for them. This needs a better solution then simply looking for each component if it is available or not.

**Pull request closed without merging**
