### PR TITLE
unknown-horizons pep8 conform

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
spaces for tabs, all line lower then 80 char long, automatic test: https://travis-ci.org/MarkusHackspacher/unknown-horizons
the code checking is in https://github.com/MarkusHackspacher/unknown-horizons/blob/master/tests/unittests/test_pep8.py
And is check by quantifiedcode.com:
https://www.quantifiedcode.com/app/project/dfb8434844b0481d9328975c88c8d703

### CODE REVIEW

**Comment by stubb** [comment]
Thanks for your work! Sadly it seems you missed our coding style wiki page? https://github.com/unknown-horizons/unknown-horizons/wiki/Coding-style

Before we will merge your PR you should revert the changes that replaces the tabs with spaces. Everything else seems to fit the requirements. Having a line length of 79 chars is fine in my opinion.

**Comment by MarkusHackspacher** [comment]
I change tabs for space in file run_tests.py and tests/unittests/test_pep8.py, but I the testing at https://travis-ci.org/MarkusHackspacher/unknown-horizons show  me at line 693 to 732 and from 759 to 854 for each line in the code `W191 indentation contains tabs` or `E101 indentation contains mixed spaces and tabs`. 
Have anybody a idea to turn off this message?

**Comment by stubb** [comment]
The documentation gives some hints like http://pep8.readthedocs.org/en/latest/api.html#pep8.process_options and then providing a configuration which includes --ignore=errors

**Comment by stubb** [comment]
Would be great if you could also provide your pep8 test!

**Comment by MarkusHackspacher** [comment]
Thanks for that great idea, it works, no error/warning W191 indentation contains tabs more, but the next is the fault message line to long,
https://travis-ci.org/MarkusHackspacher/unknown-horizons#L717
but the line is 88 long, the other line with 87 is good, without a message
https://github.com/MarkusHackspacher/unknown-horizons/blob/master/tests/unittests/test_pep8.py#L89-L90
Tabs would not count in the line, it works with spaces.

Have you a idea?

**Comment by ChrisOelmueller** [comment]
An angry comment by me was requested, so here we go:

Did you even read any of the comments in the old threads? ( #2289 and especially #2290 )
PEP-8 isn't actually the project's coding style. Why did you introduce those changes?
Who do you expect to review such a massive PR with mostly empty commit messages?

Opening pull requests is good in theory, but this one is doing more harm than good by quite a margin. If you have any other questions, feel free to post them here and I'll ignore them for a year and a half!

**Comment by MarkusHackspacher** [comment]
Of course, I know the old comments,

The decision was personally to prove to me that it is possible also a great project to reformat the code to PEP-8.
I see my PR as preview and source of ideas.

**Comment by MarkusHackspacher** [comment]
The New Python release will be Python 8.
With the new Python 8 is it not possible to import a module which does not respect the PEP 8.
https://mail.python.org/pipermail/python-dev/2016-March/143603.html

**Pull request closed without merging**
