### PR TITLE
Fixed the tooltips

### PR DESCRIPTION
**Pull request by Gladius1**
Finally got the time to fix the tooltips. I hope everything works as intended

### CODE REVIEW

**Comment by stubb** [comment]
Thanks for this PR :+1: 
Can you elaborate which problems you tried to fix? Maybe there is already an issue covering the topic.

**Comment by Gladius1** [comment]
Well for once the width of the tooltips was off:
 Tooltips width is not correct #2338 

Also the tooltips sometimes wouldn't dissappear. This was fixed for the inventory resource tooltips, but not for the island resource tooltips.
 Inventory resource hovered message not dismissed #2227

**Comment by Gladius1** [comment]
The fix doesn't work well for very small buttons, this will have to be fixed at some time. Maybe when styles are fully implemented in pychan. For now this was the best I was capable of.

**Comment by Gladius1** [comment]
I just realized that it is still possible to get a tooltip stuck by moving the mouse very fast over a button with a tooltip. So this is no complete fix just a mend.

**Comment by stubb** [comment]
Seems like for some tooltips the width does not fit yet.

**Comment by Gladius1** [comment]
I can't replicate this. Are you using the newest commit?

**Comment by stubb** [comment]
Yes, i used your recent commits. Maybe iam using an new version of fifechan/fifengine. Was there a special reason you close this issue?

**Comment by Gladius1** [comment]
I thought that since there are still some fixes to be made, I should commit to a branch and not master. Until all bugs are fixed I'll code on the branch:
https://github.com/Gladius1/unknown-horizons/tree/tooltip-fix-gladius

**Comment by stubb** [comment]
That sounds like a good idea!

**Pull request closed without merging**
