### PR TITLE
Issue #2219 - adjust labels and positioning of trade slots.

### PR DESCRIPTION
**Pull request by LinuxDonald**

### CODE REVIEW

**Comment by squiddy** [comment]
Why is this being merged when tests fail?

**Comment by LinuxDonald** [comment]
Tests fails on master too before this merge. They dont have something todo with this pr.

**Comment by squiddy** [comment]
Well, fix tests on master then? Our have you checked that this PR didn't introduce new issues?

**Comment by LinuxDonald** [comment]
I dont have seen an new errors.

**Comment by AndyMender** [comment]
`isort -c -rc horizons tests *.py` ran locally doesn't produce the errors that pop up on Travis CI.

**Comment by LinuxDonald** [comment]
@squiddy i think it have something todo with the prebuild fife package from @MasterofJOKers not any code change on our side.

**Comment by squiddy** [comment]
Ok. Can't check right now, but my guess is that the Fife package is put into a different import group (stdlib, third party, own) now and therefore isort notices seemingly wrong orders. The group can be overridden in isorts config though.

**Comment by MasterofJOKers** [comment]
fife is configured in isort's config as "known_third_party": `known_third_party = fife`

**Comment by squiddy** [comment]
So the issue is that `typing` is only included in Python 3.5 and newer. Which means in 3.4 it is a third-party module and therefore sorted differently. The reason why isort doesn't warn locally is that you simply haven't been developing against Python 3.4. If that's the version we're going to support, we should probably develop against that.

For now, I'm declaring typing as known standard library for isort so travis checks should be fixed then. Before packaging the next release, we need to make sure to include the dependency on typing.

**Pull request merged**
