### PR TITLE
When the cursor is over the editor widget, the cursor changes back to…

### PR DESCRIPTION
**Pull request by LinuxDonald**
… an arrow, rather than a tile.

@MasterofJOKers what do you thinking about that code?

### CODE REVIEW

**Comment by MasterofJOKers** [comment]
@LinuxDonald The code looks OK to me. It does things like I would do them with my current knowledge. At least as far as I understand the problem and without looking further into the issue. I would probably rename the methods and make them private. And there seems to be a different indentation in the second `mapEvents`. Also, I don't know why the second `mapEvents` is needed, but that might be, because I don't know the GUI/workflow that this commit changes.

**Comment by LinuxDonald** [comment]
Thx for the info. I will test the changes from here and post my feedback.

**Comment by MasterofJOKers** [comment]
Rebased onto current master ...

**Comment by LinuxDonald** [comment]
Tested. Works very good and an nice enhancement :)

@ThePawnBreak thx for this :)

@MasterofJOKers thx for fixing it up :)

**Pull request merged**
