### PR TITLE
Fix #2242 (Trade Tutorial Confusing)

### LINKED ISSUE #2242: Trade Tutorial Confusing
This was my first time trying out the game and most of the tutorial was pretty straight forward except for the trading. The text starts off with "After selecting a particular type of good," but it didn't really explain where you're supposed to see this.

At this point in the tutorial I didn't get that you had to select the warehouse to see trade information. Similarly, it took me more time to realize you have to select the main square to see tax information.

I'd recommend adding a line at the start of the trade tutorial like "First, select your warehouse.". 

Also, wasn't quite clear how the GUI works to setup a trade. Maybe something like this can help explain it: "Click the one of the open spots in the trade menu to choose a good to buy or sell"

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2969472-trade-tutorial-confusing?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LinuxDonald**
Fix #2242 (Trade Tutorial Confusing)

Only update of the translations files are needed.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@ChrisOelmueller how i can update the translations files because: ./development/update_translations.py give me that error:
Traceback (most recent call last):
  File "./development/update_translations.py", line 30, in <module>
    from horizons.constants import LANGUAGENAMES
ImportError: No module named horizons.constants

**Comment by ChrisOelmueller** [comment]
@LinuxDonald 
Hmm, that script is all I know about, sorry. Last time I ran it myself, it seems to have worked still. Did anything about importing `horizons` change in the interim?

**Comment by LinuxDonald** [comment]
I don't think that there was an change. I will took later again on it.

**Comment by LinuxDonald** [comment]
@ChrisOelmueller i dont think th script have updated it correctly? i miss the new strings...

**Comment by LinuxDonald** [comment]
the most scripts in development cant be excuted without errors... what im doing wrong??

**Comment by LinuxDonald** [comment]
eoc can you please review that before i rebase this...

**Comment by ChrisOelmueller** [comment]
I'm not sure what you're asking me to do. What I can tell you is that the overall Diff looks pretty wrong. What I cannot tell you is how to fix the issues you're running into, as I have neither resources nor time nor information to do so.

I'll unsubscribe from this thread.

**Pull request closed without merging**
