### PR TITLE
fix issue #2315 to prevent double hide of current_tab of TabWidget

### PR DESCRIPTION
**Pull request by pinkfloyda**
fix crash issue #2321 and #2315, and close mem-leak issue #2308

### CODE REVIEW

**Comment by stubb** [comment]
Just gave your PR a try it produces the same crash as before here.

**Comment by pinkfloyda** [comment]
This pull request updated, pls try and merge if ok

**Comment by stubb** [comment]
Thanks for further investigation. But it seems like its not yet fixed completly. I ran the gui tests and it seems like some tests of the editor are failing now with your PR:

```ERROR: Test that tiles are placed while dragging the mouse.
----------------------------------------------------------------------
TestFailed: 

Traceback (most recent call last):
  File "run_uh.py", line 380, in <module>
    main()
  File "run_uh.py", line 189, in main
    ret = horizons.main.start(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 236, in start
    startup_worked = edit_map(command_line_arguments.edit_map)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 552, in edit_map
    return _edit_map(_find_matching_map(map_name, SavegameManager.get_maps()))
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 542, in _edit_map
    start_singleplayer(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 378, in start_singleplayer
    _modules.session.load(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/session.py", line 51, in load
    self.ingame_gui.setup()
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 137, in setup
    self._settings_tab = TabWidget(self, tabs=[SettingsTab(self.session.world_editor, self)])
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 211, in __init__
    b = self.widget.findChild(name='size_%d' % i)
AttributeError: 'str' object has no attribute 'findChild'


------------------------ >> rerun the test << ------------------------
python2 run_tests.py tests.gui.test_editor:test_drag_mouse -a gui

======================================================================
ERROR: Place different tiles with different tile sizes.
----------------------------------------------------------------------
TestFailed: 

Traceback (most recent call last):
  File "run_uh.py", line 380, in <module>
    main()
  File "run_uh.py", line 189, in main
    ret = horizons.main.start(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 236, in start
    startup_worked = edit_map(command_line_arguments.edit_map)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 552, in edit_map
    return _edit_map(_find_matching_map(map_name, SavegameManager.get_maps()))
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 542, in _edit_map
    start_singleplayer(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 378, in start_singleplayer
    _modules.session.load(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/session.py", line 51, in load
    self.ingame_gui.setup()
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 137, in setup
    self._settings_tab = TabWidget(self, tabs=[SettingsTab(self.session.world_editor, self)])
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 211, in __init__
    b = self.widget.findChild(name='size_%d' % i)
AttributeError: 'str' object has no attribute 'findChild'


------------------------ >> rerun the test << ------------------------
python2 run_tests.py tests.gui.test_editor:test_place_tiles -a gui

======================================================================
ERROR: Save a map in the editor.
----------------------------------------------------------------------
TestFailed: 

Traceback (most recent call last):
  File "run_uh.py", line 380, in <module>
    main()
  File "run_uh.py", line 189, in main
    ret = horizons.main.start(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 236, in start
    startup_worked = edit_map(command_line_arguments.edit_map)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 552, in edit_map
    return _edit_map(_find_matching_map(map_name, SavegameManager.get_maps()))
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 542, in _edit_map
    start_singleplayer(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/main.py", line 378, in start_singleplayer
    _modules.session.load(options)
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/session.py", line 51, in load
    self.ingame_gui.setup()
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 137, in setup
    self._settings_tab = TabWidget(self, tabs=[SettingsTab(self.session.world_editor, self)])
  File "/home/kili/Repositories/unknown-horizons/horizons/editor/gui.py", line 211, in __init__
    b = self.widget.findChild(name='size_%d' % i)
AttributeError: 'str' object has no attribute 'findChild'


------------------------ >> rerun the test << ------------------------
python2 run_tests.py tests.gui.test_editor:test_save_map -a gui

```

**Comment by pinkfloyda** [comment]
ok, i see, looks some places dun recognize lazy_loading, i will take a look

**Comment by pinkfloyda** [comment]
updated, tested with automation, seems ok, also fixes automation errors. but still have 5 errors

**Comment by stubb** [comment]
Great work! The other errors seem unrelated to your PR.

**Comment by LinuxDonald** [comment]
can that be closed?

**Pull request merged**
