### PR TITLE
Refactor ship_map update by subclassing properties.

### PR DESCRIPTION
**Pull request by icyvapor**
- Making the variables 'position' and '_next_target' in movingobject.py into properties.
- Overriding the setters for the new properties in ship.py, so when they are set, ship_map gets updated.
- Clean up ship_map updates made unnecessary by the properties setters.

-  Removed 'is_ship' and 'is_unit' in unit.py. Their purpose can be achieved by using type().

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@squiddy have you maybe time for review this please?

@icyvapor to answer your question from irc: Travis/Tests are still broken i will fix this this week.

**Comment by LinuxDonald** [comment]
Ticket for this PR: #1684

**Comment by icyvapor** [comment]
Actually I started seeing the same type of errors when I tried to run uh locally.. Was there a required dependency upgrade I'm missing? 

And looking at the Travis logs.. my changes aren't exactly working.. I'll fix them first, so maybe review can be hold off a bit.

**Comment by LinuxDonald** [comment]
You need lastest fife git version for uh git version. Travis is broken. Because it uses not the lastest git version of fife

**Comment by LinuxDonald** [comment]
@icyvapor any news here? :)

**Comment by icyvapor** [comment]
Ah sorry, I was a bit distracted by other things lately, and I underestimated the complexity of this task.
I'll continue this week(end).

**Comment by LinuxDonald** [comment]
Thank you for the info :)

**Comment by LinuxDonald** [comment]
@icyvapor any update about this?

**Comment by icyvapor** [comment]
Hi Thomas, terribly sorry... I won’t have time to work here before end of
this month..
Anyway to shelf or abandon this? I modified a bit too much than I’m
familiar with ..

**Comment by AndyMender** [comment]
@icyvapor leave it for now. Once we fix the tests and get new versions of fifengine and fifechan on the server, things will move much more smoothly.

**Comment by jmdejong** [comment]
You should use `isinstance(collector, Ship)` instead of `type(collector) is Ship`.
Comparing the type will fail for subclasses of Ship (like TradeShip).
Using `isinstance` will properly detect an instance of TradeShip as a Ship.

**Comment by LinuxDonald** [comment]
@jmdejong you can fork this pr and make it final. I dont think that the person who started this. Dont ork active on this.

**Comment by icyvapor** [comment]
Yeah, again sorry for not picking this up later.. 
Let me know if I can do anything to help here..

**Comment by LinuxDonald** [comment]
@icyvapor it's okay :-) @jmdejong have time :-P he can made this pr done :-)

**Pull request closed without merging**
