### PR TITLE
start of porting UH to use new pychan version

### PR DESCRIPTION
**Pull request by LinuxDonald**
Started to port UH to use the new pychan version.

- [x] Hotkey menu ist broken
- [x] Resbar is broken
- [x] Build menu is broken
- [x] Production Overview on Buildings is broken
- [ ] Tooltips dont get removed sometimes for exsample in hotkey menu

and more...

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Minimapo bring the game to crash. Dont know why.

```
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
libGL: pci id for fd 6: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 175, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 355, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable                                                                                                                                                                        
    return func(*args,**kwargs)                                                                                                                                                                                                                                                
 File "/home/linuxdonald/dev/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__                                                                                                                                                                          
    return self.callback(*self.args, **self.kwargs)                                                                                                                                                                                                                            
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 104, in _select_mode                                                                                                                                                             
    self._mode.show()                                                                                                                                                                                                                                                          
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 405, in show                                                                                                                                                                     
    self._update_map_infos()                                                                                                                                                                                                                                                   
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 418, in _update_map_infos                                                                                                                                                        
    self._update_map_preview(map_file)                                                                                                                                                                                                                                         
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 442, in _update_map_preview                                                                                                                                                      
    preview=True)                                                                                                                                                                                                                                                              
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 184, in __init__                                                                                                                                                                          
    self._update_world_to_minimap_ratio()                                                                                                                                                                                                                                      
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 747, in _update_world_to_minimap_ratio                                                                                                                                                    
    self._world_to_minimap_ratio = get_world_to_minimap_ratio(world_dimensions, minimap_dimensions)                                                                                                                                                                            
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 44, in get_world_to_minimap_ratio                                                                                                                                                         
    return tuple(float(w) / m for w, m in zip(world_dimensions, minimap_dimensions))                                                                                                                                                                                           
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 44, in <genexpr>                                                                                                                                                                          
    return tuple(float(w) / m for w, m in zip(world_dimensions, minimap_dimensions))                                                                                                                                                                                           
ZeroDivisionError: float division by zero                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "./run_uh.py", line 380, in <module>                                                                                                                                                                                                                                    
    main()                                                                                                                                                                                                                                                                     
  File "./run_uh.py", line 190, in main                                                                                                                                                                                                                                        
    ret = horizons.main.start(options)                                                                                                                                                                                                                                         
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 247, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 279, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 286, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2713, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
[linuxdonald@linuxdonald-pc unknown-horizons]$ 
```

**Comment by helios2000** [comment]
Why do you start from scratch again? We already fixed that in the other branch. And probably a few other errors too.

**Comment by LinuxDonald** [comment]
With this branch i want to make an cleaner port.

**Comment by LinuxDonald** [comment]
@helios2000 how we fixed this?

**Comment by helios2000** [comment]
https://github.com/unknown-horizons/unknown-horizons/compare/pychan#diff-f574c746f40f2621aab36825a4ea4253R50

**Comment by LinuxDonald** [comment]
@helios2000 it dont fix the crash :(

**Comment by LinuxDonald** [comment]
Inagme crash when click on player ship:

```
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
libGL: pci id for fd 6: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
    self.apply_select()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 151, in apply_select
    iter(selected).next().get_component(SelectableComponent).show_menu()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/component/selectablecomponent.py", line 94, in show_menu
    tabwidget = TabWidget(self.session.ingame_gui, tabs=tabs, active_tab=active_tab_index)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 53, in __init__
    self.current_tab.ensure_loaded() # loading current_tab widget
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 163, in ensure_loaded
    self._setup_widget()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 102, in _setup_widget
    self.init_widget()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 50, in init_widget
    self.route_menu = RouteConfig(self._windows, self.instance)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 67, in __init__
    self._init_gui()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 431, in _init_gui
    on_click=self.on_map_click)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 184, in __init__
    self._update_world_to_minimap_ratio()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 747, in _update_world_to_minimap_ratio
    self._world_to_minimap_ratio = get_world_to_minimap_ratio(world_dimensions, minimap_dimensions)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 44, in get_world_to_minimap_ratio
    return tuple(float(w) / m for w, m in zip(world_dimensions, minimap_dimensions))
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 44, in <genexpr>
    return tuple(float(w) / m for w, m in zip(world_dimensions, minimap_dimensions))
ZeroDivisionError: float division by zero

Traceback (most recent call last):
  File "./run_uh.py", line 380, in <module>
    main()
  File "./run_uh.py", line 190, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 247, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 279, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 286, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2713, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
[linuxdonald@linuxdonald-pc unknown-horizons]$ 
```

**Comment by LinuxDonald** [comment]
Cleanup posts

**Comment by LinuxDonald** [comment]
why we need this? https://github.com/unknown-horizons/unknown-horizons/blob/d3f394a2c9a43f3c32c64e33042040f03f080912/horizons/gui/widgets/logbook.py#L220

**Comment by MasterofJOKers** [comment]
This is a helper function to create a `Label` later on. We need this, so we don't have to repeat the same arguments over and over again. Instead, this function only takes the dynamic arguments of a label (`text` and maybe `font`) and creates a new `Label` with that text and other default parameters (`max_size`, `wrap_text=True`, etc.).

It is used later on:
https://github.com/unknown-horizons/unknown-horizons/blob/d3f394a2c9a43f3c32c64e33042040f03f080912/horizons/gui/widgets/logbook.py#L231
https://github.com/unknown-horizons/unknown-horizons/blob/d3f394a2c9a43f3c32c64e33042040f03f080912/horizons/gui/widgets/logbook.py#L233
https://github.com/unknown-horizons/unknown-horizons/blob/d3f394a2c9a43f3c32c64e33042040f03f080912/horizons/gui/widgets/logbook.py#L249

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifengine/commit/ef3fbc35b51c53acf2f94754d7a880dafd826ae4

**Comment by LinuxDonald** [comment]
The Number under the res icons looks wrong anyone an idea why?
https://abload.de/img/2017-02-19.15-25-03.9vysrv.png

All Tabs looks cuted where can i change the size of the tabs?
https://abload.de/img/2017-02-19.15-25-19.0oysgm.png

@MasterofJOKers @squiddy @stubb 
Anyone of you an idea?

**Comment by LinuxDonald** [comment]
@helios2000 maybe you can do some review?

**Comment by helios2000** [comment]
Well, as the main changes are only xml related, I can not say much. If the values work it's ok.

**Pull request merged**
