### PR TITLE
Remove _modules in main.py and fix global variable usage

### PR DESCRIPTION
**Pull request by icyvapor**
I started looking at the code base again, and noticed the _modules is just a thin-wrapper that isn't very meaningful. With it, everywhere when 'gui' or 'session' is referenced, there needs to be a '_modules' in front of it, which increase code clutter. 

So I decided to clean it up, and then realised I need to use 'global' statements in the functions in main.py so the global variables take effect. 

While doing this, I noticed other global variables that has not been declared as 'global' in some functions (e.g. quit() ). It's also been fixed. 

Lastly minor typo in the docs for starter task label. 

This is my first pull request ever, so let me know if I missed anything. 

Cheers!

### CODE REVIEW

**Comment by icyvapor** [comment]
Seems these are the same failures seen here : 
https://travis-ci.org/unknown-horizons/unknown-horizons/builds/288262454?utm_source=github_status&utm_medium=notification

@LinuxDonald  ? :)

**Comment by LinuxDonald** [comment]
Yeah our fife Version on travis is to old at the moment.

**Comment by LinuxDonald** [comment]
@mender27 have you time for an review?

**Comment by LinuxDonald** [comment]
Merge with cherry-pick:

https://github.com/unknown-horizons/unknown-horizons/commit/306003f381f2da417104334a215ab47a0335c05e
https://github.com/unknown-horizons/unknown-horizons/commit/537da1324d8e24cda00a37fe6b9e7fd7f7ace0c2

**Comment by LinuxDonald** [comment]
Thank you for the pr :) Please next time dont do this:
Merge remote-tracking branch 'upstream/master'

Its not nice for merging pr.
But its not an big problem.
We hope that we will see some more prs from you hopfully.

**Comment by icyvapor** [comment]
hmm I'm a bit confused: 
I did that simply to update my forked code base with the more recent commits on "unknown-horizons/unknown-horizons". 
What's the proper way if I want to sync new changes happened in "unknown-horizons/unknown-horizons" into my  "icyvapor/unknown-horizons" ? 

Cheers!

**Comment by LinuxDonald** [comment]
You don't need to update when you are working on an pr. Or maybe git rebase could help too. Are you planning todo more prs for this project?

**Comment by icyvapor** [comment]
Yeah, totally. =)

**Pull request closed without merging**
