### PR TITLE
Fix translate

### PR DESCRIPTION
**Pull request by LinuxDonald**
This should fix that some strings was not translatable.

@jorgesumle i hope this will fix the problem :)

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@ChrisOelmueller why you comment line 71 here? 8cc6aeab4c25a3305b9e7b274a9934610b1fbada

I uncomment it and now the scripts find more strings.

**Comment by ChrisOelmueller** [comment]
The way I remember it, I wanted more control over when/whether the
commented commands in the script were executed, so I'd uncomment them
locally as needed.

**Comment by LinuxDonald** [comment]
Thx for the information :-) I will merge that later today.

**Comment by MasterofJOKers** [comment]
We could add commandline options for the commented commands, so control is there and no commenting has to happen.

**Comment by LinuxDonald** [comment]
@MasterofJOKers feel free to do an improvemd here. For now i merged only the updatet translations.

**Comment by jorgesumle** [comment]
But if you add the # back, you have to remove it again when you want to update the interface translations, don't you? If you let it uncommented it should works always.

**Comment by LinuxDonald** [comment]
This line is only needed if we add for example new building to the game. I want to wait what @MasterofJOKers want todo here.

**Comment by squiddy** [comment]
What's the status here? @LinuxDonald you mentioned that the translations are already merged, is this only about the commented/uncommented line? Anyone working on this or can it be closed?

**Comment by MasterofJOKers** [comment]
Looking at it, I'm supposed to do something: add commandline options to update_translations.py. I'll open a ticket for that.

**Pull request closed without merging**
