### PR TITLE
GUI Button sounds

### PR DESCRIPTION
**Pull request by Gladius1**
Implemented button sounds

### CODE REVIEW

**Comment by stubb** [comment]
Thanks for this PR. Seems like its kind of messed up. I recommend to store all relevant commits as diff.
Use the github link and append .diff https://github.com/Gladius1/unknown-horizons/commit/b7cc9318e8bcf0727c5486bd8014b0560b31d368 to https://github.com/Gladius1/unknown-horizons/commit/b7cc9318e8bcf0727c5486bd8014b0560b31d368.diff 

Make a new fork of the master branch of unknown horizons. Afterwards use git apply patch-file to apply your patch files. And then make a complete new Pull request. I think that is the easiest way to get a clean repository.

**Comment by LinuxDonald** [comment]
Gladius1 please check this https://github.com/unknown-horizons/unknown-horizons/pull/2337
Is it alle correct?

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2337

**Comment by LinuxDonald** [comment]
merged into master

**Pull request closed without merging**
