### PR TITLE
Add building barrier. WIP.

### PR DESCRIPTION
**Pull request by stubb**
- [ ] Needs proper description within the object file.
- [ ] Buildmenu icons.
- [ ] GFX
- [ ] Overview Tab should have title, health, description & image.

### CODE REVIEW

**Comment by stubb** [comment]
The GFX needs to be 1x1, because there is a "missing feature" within the related code https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/world/building/buildable.py#L375

**Comment by LinuxDonald** [comment]
i hope my work helps you a bit :)

**Comment by stubb** [comment]
For sure! :+1:

**Comment by stubb** [comment]
@LinuxDonald was there a special reason to update the enum.py within this branch?

**Comment by LinuxDonald** [comment]
No sorry I had forgotten to change the branch to master on local

**Comment by stubb** [comment]
Closed, please use the branch barrier_building.
Updating enum is not allowed, because its licence switched from gpl2+ to gpl3. This requires glp3 for Unknown Horizons to be able to include this code.

**Pull request closed without merging**
