### PR TITLE
Fixed Version info.

### PR DESCRIPTION
**Pull request by lahtis**
All translations into Finnish have been translated. 100% in weblate. Please backup to project.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
I will take an look into weblate. Than it should merge again the weblate translation updates in our repo.

**Comment by lahtis** [comment]
ok.

During this Corona time it is nice to do such community work.

2020-03-28 13:45 UTC+02.00, Thomas Kowaliczek-Schmer <notifications@github.com>:

**Comment by LinuxDonald** [comment]
I sync it now manually. At the moment I don't know how to repair it.

**Comment by LinuxDonald** [comment]
Should be fixed now.

**Pull request closed without merging**
