### PR TITLE
Remove an unnecessary `pass` statement

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
'pass' is not needed in this context.

And have comment tow classes.

I hope that is ok.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Give it any way to test this?

**Comment by MasterofJOKers** [comment]
What's that "test_noneStance.py" for?

**Comment by MarkusHackspacher** [comment]
test_noneStance.py is a simple test case to test the class noneStance work without 'pass'.
I hope it is the right way that for the question of @LinuxDonald 'Give it any way to test this?'

**Comment by MasterofJOKers** [comment]
I think the output of `from horizons.component.stancecomponent import NoneStance` would have sufficed.

**Comment by MarkusHackspacher** [comment]
I simulate an error in the class NoneStance, you see below the Traceback.
The fault was detected. But the Traceback shows not the fault, it shows something.
https://travis-ci.org/MarkusHackspacher/unknown-horizons/builds/151006848

The simulation show my changes to remove the 'pass' don't break the project.
But is something wrong in the future at this part the Travis CI can not detect the fault, maybe a test with like ' test_noneStance.py' only better is not wrong.

Please make a suggestion how to continue?

----------------------------------------------------------------------

ERROR: Check if traderoutes do anything.

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/tests/game/__init__.py", line 256, in wrapped

    s = load_session(path)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/tests/game/__init__.py", line 209, in load_session

    session.load(savegame, [], False, is_map)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/tests/game/__init__.py", line 123, in load

    super(SPTestSession, self).load(options)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/horizons/spsession.py", line 44, in load

    super(SPSession, self).load(*args, **kwargs)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/horizons/session.py", line 280, in load

    disasters_enabled=options.disasters_enabled)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/horizons/world/__init__.py", line 234, in _init

    Entities.units[typeid].load(self.session, savegame_db, worldid)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/horizons/world/ingametype.py", line 58, in load

    super(cls, self).load(db, worldid)

  File "/home/travis/build/MarkusHackspacher/unknown-horizons/horizons/world/units/weaponholder.py", line 617, in load

    self.stance.set_state(state)

AttributeError: 'NoneType' object has no attribute 'set_state'

**Comment by MarkusHackspacher** [comment]
I remove the test.

But other question, where is the right directory for modul funtions tests? I have not see it.
I think we need more modul funtions tests, in the future.
And because in Python 2 are 5/2 = 2 in Python 3 are 2.5.

**Comment by squiddy** [comment]
> But other question, where is the right directory for modul funtions tests? I have not see it.

I think `tests/unittests/` is the right place. What did you plan to test, and why didn't you find a fitting directory? Perhaps we can clarify the naming here or add more directories.

> I think we need more modul funtions tests, in the future.

Tests are (almost) always welcome. :)

**Comment by squiddy** [comment]
Merged. Thanks.

**Pull request closed without merging**
