### PR TITLE
Simplify map preview [NOT DONE]

### PR DESCRIPTION
**Pull request by squiddy**
**(Don't merge yet.)** This serves as a reminder to me that i've been working on this. Perhaps someone else feels like looking over these changes, IIRC I already got some feedback on IRC.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Any news here?

**Comment by LinuxDonald** [comment]
Closing it and open an Issue for it: https://github.com/unknown-horizons/unknown-horizons/issues/2408

**Comment by LinuxDonald** [comment]
Reopened it because @squiddy want to work on this.

**Comment by squiddy** [comment]
> Reopened it because @squiddy want to work on this.

I may be misunderstanding you, but I didn't say anywhere I was going to work on this. If this is a suggestion what I could work on, fair enough.

However, I'm currently trying to cut down on both open issues and open pull requests. Especially bugs and crashes. So while this PR is something I'd like to deal with at some point, I don't think it's important right now.

Closing it again, but don't worry, I still have it on my radar.

**Pull request closed without merging**
