### PR TITLE
Requirements Status

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
a badge to show the versions in the requirements.txt
https://requires.io/github/MarkusHackspacher/unknown-horizons/requirements/

If the team sees it useful, as team can log on to the service and make a proper one.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Thx for this :)

**Comment by squiddy** [comment]
I don't find it that useful to be honest. Most of the requirements are for development only, and adding yet another badge? What's the purpose?

**Comment by LinuxDonald** [comment]
sorry for to fast merging.

**Comment by squiddy** [comment]
Nah, no need to be sorry. I didn't mean to sound too negative. :)

**Comment by LinuxDonald** [comment]
I have reverted it :-)

**Pull request merged**
