### PR TITLE
Use up-to-date python libs on travis

### PR DESCRIPTION
**Pull request by LinuxDonald**
@squiddy on travis its green :) is it okay for merging into master?

### CODE REVIEW

**Comment by squiddy** [comment]
I think I'd prefer the packages to be pinned to specific versions. Otherwise for example Travis might be failing randomly because it fetched a new version that isn't backwards compatible. 

We still can update the packages though while we're at it.

**Comment by LinuxDonald** [comment]
Want we then pin they to the yet newest version?

**Comment by squiddy** [comment]
Yes. Preferably a stable version.

**Comment by squiddy** [comment]
I've thought about it, let's just remove the versions. You have to rebase onto master first to resolve conflicts.

**Pull request closed without merging**
