### PR TITLE
Rewrite step slider to accept discrete steps on construction

### PR DESCRIPTION
**Pull request by squiddy**
Externally, the slider accepts either a semicolon separated list of
steps or a list of numeric values. Reading and writing the value of the
slider works with the discrete values defined in steps.

Refs #1957 

---
### Short demo

https://www.youtube.com/watch?v=7WKlhEvzFTA
### TODO
- [x] Figure out how to handle old settings files (they stored the slider value, which on master is anything between 0 and 4, e.g. 3.4, which doesn't map to our discrete values)

### CODE REVIEW

**Comment by LinuxDonald** [comment]
I don't know if we need support for old settings file. Because old savegames are broken too. Only an check would be good that replace the old setting part with the new one.

**Comment by LinuxDonald** [comment]
I become that warning with old setting file on the new game random map. Playing around with the slider.

> Traceback (most recent call last):
>   File "./run_uh.py", line 382, in <module>
>     main()
>   File "./run_uh.py", line 191, in main
>     ret = horizons.main.start(options)
>   File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 108, in start
>     horizons.globals.fife = Fife()
>   File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 48, in __init__
>     self._setting = Settings(PATHS.USER_CONFIG_FILE, PATHS.SETTINGS_TEMPLATE_FILE)
>   File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/settings.py", line 42, in __init__
>     self._settings_serializer.load(settings_file)
>   File "/usr/lib/python2.7/site-packages/fife/extensions/serializers/simplexml.py", line 121, in load
>     self._tree = ET.parse(self._file)
>   File "<string>", line 62, in parse
>   File "<string>", line 38, in parse
> cElementTree.ParseError: no element found: line 1, column 0

**Comment by LinuxDonald** [comment]
I become this warning when i load an old savegame with old seetings file.
First load old savegame. Close it and open new game go random map:

> Traceback (most recent call last):
  File "./run_uh.py", line 382, in <module>
    main()
  File "./run_uh.py", line 191, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 113, in start
    command_line_arguments.generate_minimap
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 627, in generate_random_minimap
    world = load_raw_world(map_file)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 744, in load_raw_world
    world.load_raw_map(SavegameAccessor(map_file, True), preview=True)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/util/savegameaccessor.py", line 90, in __init__
    create_random_island(random_map_db, island_id, island_string)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/util/random_map.py", line 45, in create_random_island
    assert match_obj
AssertionError

**Comment by squiddy** [comment]
> I get that warning with old setting file on the new game random map. Playing around with the slider.

I can't reproduce this, can you show the steps you've taken? This is what I did:

1. Checkout master
2. Open random map menu
3. Play around with sliders (settings.xml shows values between 1.0 and 4.0 for the various random map paramteres)
4. Checkout this branch
5. Play around with sliders

**Comment by squiddy** [comment]
> I get this warning when i load an old savegame with old seetings file.
> First load old savegame. Close it and open new game go random map:

Can't reproduce this either. What I did:

1. Checkout master
2. Create new random map
3. Save the game
4. Checkout this branch
5. Load the game
6. End the game
7. Create new random map

No warnings, no errors here.

**Comment by LinuxDonald** [comment]
I maked an video on the one warning because i become it every time. https://youtu.be/1G3-r5Hcg1w

**Comment by squiddy** [comment]
@LinuxDonald It's not that I don't believe that you're seeing warnings, but I can't reproduce them. The video doesn't help with that. Do you get the same warnings when doing the exact steps I outlined? Perhaps we need more people to try this.

**Comment by LinuxDonald** [comment]
Okay found the problem. This pr can get merged. The Problem was my seetings.xml i think it was broken. Removed it and no errors on master and this pr.

**Comment by squiddy** [comment]
Merged in 60d74f18bb4a6feaf1de4551087892c8b84d190c

**Pull request closed without merging**
