### PR TITLE
Simplify explicit super() calls.

### PR DESCRIPTION
**Pull request by AndyMender**
This is an attempt to reduce the explicit calls `super(ChildClass, self).superclass_method()` to `super().superclass_method()`, as per changes in Python3 the `superclass_method` is bound to the instance of `ChildClass` by default. This does not touch cases when the `superclass_method` is bound to another object like in `super(ChildClass, cls).superclass_method()`.

In the midst of my analysis I noticed cases when a base class calls `super()` on itself as in:
```python 
class A:
     def __init__(self, x, y):
         super().__init__()
         self.x = x
         self.y = y
```
The Python interpreter claims it's wrong and at first glance may lead to infinite loops regardless. These cases were labeled with a TODO comment.

### CODE REVIEW

**Comment by AndyMender** [comment]
Apparently, in cases when the `classmethod` decorator is used, my changes broke quite some tests. I will fix them soon.

**Comment by AndyMender** [comment]
I fixed the broken `super()` calls, but the surrounding code that caused the issues is really ugly and should be fixed at one point in time.

**Comment by LinuxDonald** [comment]
@AndyMender any news about that here?

**Comment by AndyMender** [comment]
@LinuxDonald , all of the tests on Travis (including the GUI tests) run fine since the last commit. When I did manual game testing after that everything was fine also. However, I do need squiddy's feedback, as some use cases of `super()` are very non-obvious, especially in multiple inheritance scenarios and considering the fact that in some of the files even `__new__` was overloaded. Not to mention that our tests don't cover everything yet.

**Pull request merged**
