### PR TITLE
Small changes to prepare python 3 support

### PR DESCRIPTION
**Pull request by squiddy**
There is more to do to make UH work with python 3, but these changes should be pretty safe.

### CODE REVIEW

**Comment by squiddy** [comment]
What's the minimum python version we're supporting?

**Comment by MasterofJOKers** [comment]
currently? 2.6. or do you mean for python3? I'd say 3.4 as it's in Debian stable.

**Comment by squiddy** [comment]
Yeah, I wanted to know versions from both 2.x and 3.x, thanks.

**Comment by MasterofJOKers** [comment]
On the other hand, 3.5 is in the next Debian stable, so that should be fine, too, if there's something worth it init.

**Comment by MasterofJOKers** [comment]
Looking at the relative import changes: Should we finally start sorting our imports?

**Comment by squiddy** [comment]
Yeah, sorting imports sounds good. isort is pretty capable. We can do this in a different PR, I'm probably going to merge this later, seeing as it won't break anything.

**Comment by jorgesumle** [comment]
>  Imports should be grouped in the following order:
> 
>     standard library imports
>     related third party imports
>     local application/library specific imports
> 
> You should put a blank line between each group of imports. 

Take this from Python style guide (PEP 8) into account: https://www.python.org/dev/peps/pep-0008/#imports.

**Comment by squiddy** [comment]
Added isort in 21c0b64984805795f0416e6c1f7c3029adc1fd14

**Pull request closed without merging**
