### PR TITLE
Python 3 Port [WORK IN PROGRESS/ DONT MERGE]

### PR DESCRIPTION
**Pull request by LinuxDonald**

### CODE REVIEW

**Comment by LinuxDonald** [comment]
We need to rebuild pyenet for multiplayer. I will do this on the next days.

**Comment by AndyMender** [comment]
I think there is a couple of things that might still need to be addressed before merging:
- issue #2637 (there are some superficial `float()` calls that can be removed; Python3 knows how to do float calculations on ints properly, etc.)
- issues #2635 and #2636 (this requires improvements to the `Dummy` object, but can probably be done; the biggest hurdle is defining `Dummy() > Dummy()` logic)
- issue #2633 (to facilitate Travis CI tests; the current workaround is to let Travis CI build FIFE for every commit; it works, but the tests are a lot slower as a result)

To be fair, however, issue #2637 can be addressed after merging and things like issue #1379 were there since forever.

**Comment by LinuxDonald** [comment]
@AndyMender could you take an look on this:

`[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
libGL: pci id for fd 6: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
Failed to load /home/linuxdonald/.unknown-horizons/save/test-py3.sqlite
Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 343, in start_singleplayer
    _modules.session.load(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/spsession.py", line 45, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 266, in load
    self.ingame_gui.load(savegame_db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 346, in load
    self.logbook.load(db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 140, in load
    self.set_cur_entry(int(value[0][0])) # this also redraws
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 336, in set_cur_entry
    raise ValueError
ValueError

Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 343, in start_singleplayer
    _modules.session.load(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/spsession.py", line 45, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 266, in load
    self.ingame_gui.load(savegame_db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 346, in load
    self.logbook.load(db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 140, in load
    self.set_cur_entry(int(value[0][0])) # this also redraws
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 336, in set_cur_entry
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 356, in start_singleplayer
    _modules.session.end()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 180, in end
    self.world.end()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 115, in end
    island.end()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/island.py", line 454, in end
    wild_animal.remove()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/resourcehandler.py", line 90, in remove
    super(ResourceHandler, self).remove()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/units/collectors/collector.py", line 103, in remove
    self.cancel(continue_action=lambda : 42)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/units/animal.py", line 256, in cancel
    super(WildAnimal, self).cancel(continue_action=continue_action)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/units/collectors/collector.py", line 439, in cancel
    assert removed_calls == 1, 'removed {} calls instead of one'.format(removed_calls)
AssertionError: removed 0 calls instead of one
Additionally to failing when loading, cleanup afterwards also failed
`

**Comment by LinuxDonald** [comment]
`Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/tools.py", line 94, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/events.py", line 194, in delayed_f
    f( event )
 File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/events.py", line 374, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/tools.py", line 71, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/gui.py", line 157, in load_game
    horizons.main.start_singleplayer(options)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 366, in start_singleplayer
    _modules.gui.load_game()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/gui.py", line 157, in load_game
    horizons.main.start_singleplayer(options)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 337, in start_singleplayer
    _modules.session = session_class(horizons.globals.db)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 110, in __init__
    self.view = View()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/view.py", line 42, in __init__
    self.map = self.model.createMap("map")
fife.fife.NameClash: _[NameClash]_ , A name or identifier is already in use :: map

Traceback (most recent call last):
  File "./run_uh.py", line 369, in <module>
    main()
  File "./run_uh.py", line 182, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 248, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 278, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 285, in loop
    self.engine.pump()
RuntimeError: Caught a director exception
`

**Comment by AndyMender** [comment]
Per a small update:
- non-GUI unit tests run both on Travis CI and locally
- GUI unit tests run only locally (issues with GLX on Travis CI) and most of them pass
- moderate-severity bugs that were there are still there and I will keep on working on them after the Python3 version is stable enough (for instance, issue #1379 
- some GUI tests fail in a non-reproducible manner
- The remaining reproducibly failing GUI test has to do with .xml formatting: https://pastebin.com/ePEfR58M @LinuxDonald could you have a look at this? :)

**Pull request merged**
