### PR TITLE
Configuration for mypy and some initial type hints

### PR DESCRIPTION
**Pull request by squiddy**
See #2513 

For the most part these changes are pretty straightforward, there is one issue however that I described in https://github.com/unknown-horizons/unknown-horizons/issues/2513#issuecomment-253968927

Some type hints require importing from the `typing` module, which we need to either add to the dependencies, ship with our code or do something entirely different.

### CODE REVIEW

**Comment by squiddy** [comment]
I might work on this during the next week, but with the exception of one issue this is good to merge: https://github.com/unknown-horizons/unknown-horizons/issues/2513#issuecomment-253968927

However we could certainly take the approach @MasterofJOKers suggested here https://github.com/unknown-horizons/unknown-horizons/issues/2513#issuecomment-253991882

```python
import my
import normal
import stuff

if False:
    from typing import Any
    from some.package.somewhere import Somethnig
```

**Comment by squiddy** [comment]
Mind you, there are still errors left to fix. We're still in phase 1 of the mypy master plan.

**Comment by ChrisOelmueller** [comment]
I'd be okay with `if False` or rather, something like this:

```py
if False: # TYPE_CHECKING
    from typing import Any
    from some.package.somewhere import Something
```

**Comment by squiddy** [comment]
I think we've come to a solution regarding the imports: https://github.com/unknown-horizons/unknown-horizons/issues/2513#issuecomment-254494723

So I'll extend this PR by doing the first 2 points, then I could merge it.

**Comment by squiddy** [comment]
I'd like to merge this as it is. It adds some type hints, but there are still many things to prepare/fix. But this serves as foundation for future work.

**Comment by squiddy** [comment]
This takes a bit longer, because now that we're including typing in horizons/ext, mypy insists on checking that file, which produces warnings.

**Comment by LinuxDonald** [comment]
Are here open questions? Or could it be merged?

**Comment by squiddy** [comment]
My comment right above yours states that there is an open issue.

**Comment by LinuxDonald** [comment]
Ah okay sorry.

**Comment by squiddy** [comment]
Merged in 0d876feeb568c2f7dc95325b6960b8830247837b.

It is unfortunate that currently mypy doesn't support excluding specific files or directories from checks, however that shouldn't stop us from adding more type hints. Errors regarding `horizons.ext` can always be ignored (grep -v).

I was tempted to go back to the `if False` approach, but mypy would still run against horizons.ext. We'll figure this out later.

**Pull request closed without merging**
