### PR TITLE
closes #2542

### LINKED ISSUE #2542: Don't place tress on sand tiles
I think it would be better if we wouldn't place trees on sand tiles, it looks a bit odd. Once we've added climate zones, we can re-enable this for desert zones with palm trees.

Game version: 36c39724b38798a5da8a54d14035750fcb67bc33
Map: development
##

### PR DESCRIPTION
**Pull request by melloskitten**
I adjusted the conditions so that there are no trees placed on sand tiles.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
It dont fix the problem completly :( Could you maybe show if you can fix this?

**Comment by melloskitten** [comment]
Which trees do you mean? The one on the coast right?

**Comment by LinuxDonald** [comment]
Yeah on the coast.

**Comment by melloskitten** [comment]
Ah! Alright I only thought you were looking for the sand tiles inside the island. I'll try to fix that too :)

**Comment by melloskitten** [comment]
it should be fixed now :)

**Comment by melloskitten** [comment]
@AndyMender Yes Exactly! It was necessary, because otherwise such corner cases as the one you see up pointed out by @LinuxDonald can happen. In one rotation it looks like the tree is completely on the coast, while as you turn it around, you suddenly see its not on the coast, but on a grass tile.

**Comment by LinuxDonald** [comment]
@melloskitten Thank you for the patch :) I hope we will see mroe patches from you :)

**Comment by AndyMender** [comment]
I'm afraid that the patch doesn't work on the py3 Python3 branch. On the "tutorial" and "The Unknown" islands I still see plenty of trees on coast-adjacent sand tiles :(.

**Comment by melloskitten** [comment]
that's sad! Sorry, I only checked out the master branch, and not the py3 one. I'll take a look at that when the py3 branch is merged :)

**Comment by melloskitten** [comment]
oh now that I think of it. Sorry, I'm still a starter / noobie - is it smarter to wait for you to finish the migration to python3 and then work on the 'starter' labeled issues, or...?

**Comment by AndyMender** [comment]
We'll be migrating to Python3 this weekend so if you could wait until then with the fix, that would be great :). I would suggest checking out the py3 branch from our repository and making sure it runs smoothly and that will be our _de facto_ main branch soon.

**Comment by melloskitten** [comment]
Aye aye! Good luck with the migration ! (migrations can be such a pain in the bum. Currently I'm also fighting with an iOS migration from swift 2 to 3 and I just want it to end lmao 😂).  I will be sure to check out those two. Thank you for your replies!

**Comment by LinuxDonald** [comment]
@melloskitten your pr works prefectly in python3 branch. My coder @AndyMender must needs an leasson how to merge correctly master in to an branch ;)

**Comment by LinuxDonald** [comment]
@melloskitten you can work on an ticket on that you are intressted. starter tickets are examples.

**Comment by AndyMender** [comment]
@melloskitten I'm terribly sorry for not merging your patch into the py3 branch properly and thanks to @LinuxDonald for correcting that. Apparently, I am still a beginner contributor ;).

**Pull request merged**
